### ISSUE TITLE
Insecure

### ISSUE THREAD

**Issue by lxi1400** [eozri/Sharex-Img-Uploader#2]
Key could be easily bruteforced, allowing you to upload whatever you want thru the upload.php

**Comment by p-qq** [comment]
I would make a js one but I am not as good with security as oxy, plus another issue is users can easily see the images you upload by making a request to the folder, they'll just need a good hosting service that doesn't leak their images folder.

**Comment by mosmiczn** [comment]
> I would make a js one but I am not as good with security as oxy, plus another issue is users can easily see the images you upload by making a request to the folder, they'll just need a good hosting service that doesn't leak their images folder.

pix when you can add my cord mxx#0002 @eozri

**Comment by p-qq** [comment]
wtf LOL whats ur cord

**Comment by xenos1337** [comment]
> I would make a js one but I am not as good with security as oxy, plus another issue is users can easily see the images you upload by making a request to the folder, they'll just need a good hosting service that doesn't leak their images folder.

you can just make a .htaccess with 
```
Deny from all
```
that should fix the images in the folder

**Comment by mosmiczn** [comment]
> wtf LOL whats ur cord

gizmo#0x002 i changed it @eozri

**Comment by xenos1337** [comment]
> > wtf LOL whats ur cord
> 
> gizmo#2 i changed it @eozri

![image](https://user-images.githubusercontent.com/66328734/116259742-5e990c00-a776-11eb-882d-911e2462c337.png)

**Comment by mosmiczn** [comment]
> > > wtf LOL whats ur cord
> > 
> > 
> > gizmo#2 i changed it @eozri
> 
> ![image](https://user-images.githubusercontent.com/66328734/116259742-5e990c00-a776-11eb-882d-911e2462c337.png)

alright hold on

**Comment by p-qq** [comment]
u can also add me pix#0070

**Comment by p-qq** [comment]
pix#0x070

**Comment by mosmiczn** [comment]
> pix#0x070

add back @eozri
