### ISSUE TITLE
Incorrect Password even if it is correct

### ISSUE THREAD

**Issue by Slddev** [eozri/Sharex-Img-Uploader#3]
# ^^^

**Comment by p-qq** [comment]
misspelled pw in .sxcu mb try it again

**Comment by Slddev** [comment]
> misspelled pw in .sxcu mb try it again

@eozri Tried again but still didn't work.

**Comment by p-qq** [comment]
add my discord pix#0070

**Comment by p-qq** [comment]
pix#0x070

**Comment by Slddev** [comment]
@eozri Accept my friend request

**Comment by Slddev** [comment]
Fixed. Forgot to put https:// before the domain in `Hoster.sxcu`
